### 📝 Register a New User
POST https://mastermind-0ex7.onrender.com/users
Content-Type: application/json

{
  "username": "suresh123",
  "name": "Nandyala Suresh",
  "email": "suresh@example.com",
  "password": "Secret123!"
}

### 🔐 Login User
POST https://mastermind-0ex7.onrender.com/login
Content-Type: application/json

{
  "username": "suresh123",
  "password": "Secret123!"
}
######
POST https://mastermind-0ex7.onrender.com/saved-courses
Content-Type: application/json
Authorization: Bearer 

{
  "course_id": "PASTE_A_MONGO_COURSE_ID_HERE" 
}
############
GET https://mastermind-0ex7.onrender.com/courses

#############
### Get all courses
GET https://mastermind-0ex7.onrender.com/courses
Accept: application/json

### Get a specific course by ID
### Get all courses with Origin
GET https://mastermind-0ex7.onrender.com/courses
Origin: http://localhost:5173

#########
GET https://mastermind-0ex7.onrender.com/courses
Accept: application/json
########
GET https://mastermind-0ex7.onrender.com/courses

#############
POST https://mastermind-2.onrender.com/courses
Content-Type: application/json

{
  "title": "Learn Node.js",
  "category": "Programming",
  "instructor": "Jane Doe",
  "rating": 4.7,
  "price": 49.99,
  "image": "https://example.com/image.jpg",
  "description": "Great Node.js course"
}
############
GET https://mastermind-2.onrender.com/courses